#define INLINE_OPTIMIZE 1	
#define ASSIGN_OPTIMIZE 1
#define ASSIGN_DELETE_OPTIMIZE 1
#define DEAD_OPTIMIZE 1
#define REG_OPTIMIZE 1
#define BRANCH_ZERO_OPTIMIZE 0
#define LOOP_OPTIMIZE 0
#define MOD_OPTIMIZE 0